# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='name',
            new_name='title',
        ),
    ]
