# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170906_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='u2r',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
