# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=47)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
