# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app02userinfo',
            name='username',
            field=models.CharField(default=1, max_length=63),
            preserve_default=False,
        ),
    ]
